// Generated by uniffi-bindgen-react-native
#include "my-test-library.h"
#include "generated/test_e2e.hpp"

namespace mytestlibrary {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeTestE2e::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}