// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "mopro-ffi.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "MoproFFISpec.h"

@interface MoproFfi : NSObject <NativeMoproFfiSpec>
#else
#import <React/RCTBridgeModule.h>

@interface MoproFfi : NSObject <RCTBridgeModule>
#endif

@end