// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "my-test-library.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "MyTestLibrarySpec.h"

@interface MyTestLibrary : NSObject <NativeMyTestLibrarySpec>
#else
#import <React/RCTBridgeModule.h>

@interface MyTestLibrary : NSObject <RCTBridgeModule>
#endif

@end