"use strict";

// Generated by uniffi-bindgen-react-native

import { TurboModuleRegistry } from 'react-native';
export default TurboModuleRegistry.getEnforcing('MyTestLibrary');
//# sourceMappingURL=NativeMyTestLibrary.js.map